name: Hello World
on: push
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello, world!"
  this-jobs:
   needs: my-jobs
   runs-on: ubuntu-latest
   steps:
   - name: this-step
     run: echo "Hello!"
